-- Source: database/schema/04_patient_tables.sql
-- รายการสภาวะและความต้องการดูแลสำหรับเลือกให้ผู้ป่วย
-- เป็นข้อมูลตัวอย่างสำหรับระบบ ไม่ใช่คำวินิจฉัยทางการแพทย์

create table public.conditions (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint conditions_name_not_blank
    check (length(btrim(name)) > 0),

  constraint conditions_description_not_blank
    check (
      description is null
      or length(btrim(description)) > 0
    )
);

create unique index conditions_name_unique
on public.conditions (lower(btrim(name)));

alter table public.conditions
enable row level security;

-- ข้อมูลผู้ป่วยที่อยู่ภายใต้การดูแลของ Employer

create table public.patients (
  id bigint generated by default as identity primary key,

  employer_id uuid not null
    references public.profiles(id) on delete restrict,

  first_name text not null,
  last_name text not null,
  birth_date date not null,
  mobility_status text not null,
  care_notes text,

  province text not null,
  district text not null,
  subdistrict text not null,
  address_detail text not null,

  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint patients_id_employer_unique
    unique (id, employer_id),

  constraint patients_first_name_not_blank
    check (length(btrim(first_name)) > 0),

  constraint patients_last_name_not_blank
    check (length(btrim(last_name)) > 0),

  constraint patients_mobility_status_valid
    check (
      mobility_status in (
        'normal',
        'bedridden',
        'wheelchair',
        'walker',
        'cane'
      )
    ),

  constraint patients_care_notes_not_blank
    check (
      care_notes is null
      or length(btrim(care_notes)) > 0
    ),

  constraint patients_address_not_blank
    check (
      length(btrim(province)) > 0
      and length(btrim(district)) > 0
      and length(btrim(subdistrict)) > 0
      and length(btrim(address_detail)) > 0
    )
);

create index patients_employer_id_idx
on public.patients (employer_id);

alter table public.patients
enable row level security;

-- ตรวจข้อมูลที่ Check Constraint แบบปกติครอบคลุมไม่ได้

create or replace function private.validate_patient()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if new.birth_date > current_date then
    raise exception using
      errcode = '23514',
      message = 'patient_birth_date_cannot_be_in_future';
  end if;

  if not exists (
    select 1
    from public.profiles
    where id = new.employer_id
      and role = 'employer'
  ) then
    raise exception using
      errcode = '23514',
      message = 'patient_owner_must_be_employer';
  end if;

  return new;
end;
$$;

create trigger patients_validate
before insert or update of birth_date, employer_id
on public.patients
for each row
execute function private.validate_patient();


-- ใช้ฟังก์ชัน updated_at ที่สร้างไว้ใน 03_updated_at_trigger.sql

create trigger conditions_set_updated_at
before update on public.conditions
for each row
execute function private.set_updated_at();

create trigger patients_set_updated_at
before update on public.patients
for each row
execute function private.set_updated_at();

-- เชื่อมผู้ป่วยกับสภาวะที่ต้องดูแล

create table public.patient_conditions (
  patient_id bigint not null
    references public.patients(id) on delete cascade,

  condition_id bigint not null
    references public.conditions(id) on delete restrict,

  created_at timestamptz not null default now(),

  primary key (patient_id, condition_id)
);

create index patient_conditions_condition_id_idx
on public.patient_conditions (condition_id);

alter table public.patient_conditions
enable row level security;


-- เชื่อมผู้ป่วยกับทักษะที่ต้องการจากผู้ดูแล

create table public.patient_required_skills (
  patient_id bigint not null
    references public.patients(id) on delete cascade,

  skill_id bigint not null
    references public.skills(id) on delete restrict,

  created_at timestamptz not null default now(),

  primary key (patient_id, skill_id)
);

create index patient_required_skills_skill_id_idx
on public.patient_required_skills (skill_id);

alter table public.patient_required_skills
enable row level security;

-- Source: database/schema/05_patient_policies.sql
-- สิทธิ์อ่านรายการสภาวะที่เปิดใช้งาน
-- RLS Policy ด้านล่างจะกรองแถวที่อ่านได้อีกชั้น

revoke all privileges
on table public.conditions
from anon, authenticated;

grant select
on table public.conditions
to anon, authenticated;


-- ผู้ใช้ที่เข้าสู่ระบบสามารถจัดการข้อมูลผู้ป่วยผ่าน RLS
-- ไม่อนุญาตให้แก้ id, employer_id และเวลาของระบบ

revoke all privileges
on table public.patients
from anon, authenticated;

grant select, insert
on table public.patients
to authenticated;

grant update (
  first_name,
  last_name,
  birth_date,
  mobility_status,
  care_notes,
  province,
  district,
  subdistrict,
  address_detail,
  is_active
)
on table public.patients
to authenticated;

grant usage, select
on sequence public.patients_id_seq
to authenticated;


-- ตารางเชื่อมจัดการได้ผ่าน RLS ของเจ้าของผู้ป่วย

revoke all privileges
on table
  public.patient_conditions,
  public.patient_required_skills
from anon, authenticated;

grant select, insert, delete
on table
  public.patient_conditions,
  public.patient_required_skills
to authenticated;

-- ทุกคนอ่านได้เฉพาะสภาวะที่เปิดใช้งาน

create policy conditions_select_active
on public.conditions
for select
to anon, authenticated
using (
  is_active = true
);


-- Employer อ่านได้เฉพาะผู้ป่วยของตนเอง

create policy patients_select_own
on public.patients
for select
to authenticated
using (
  (select auth.uid()) is not null
  and (select auth.uid()) = employer_id
);


-- Employer เพิ่มผู้ป่วยให้บัญชีของตนเองเท่านั้น

create policy patients_insert_own
on public.patients
for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and (select auth.uid()) = employer_id
  and exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'employer'
  )
);


-- Employer แก้ไขหรือปิดใช้งานผู้ป่วยของตนเองเท่านั้น

create policy patients_update_own
on public.patients
for update
to authenticated
using (
  (select auth.uid()) is not null
  and (select auth.uid()) = employer_id
)
with check (
  (select auth.uid()) is not null
  and (select auth.uid()) = employer_id
  and exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'employer'
  )
);

-- Employer อ่านสภาวะของผู้ป่วยที่ตนเองเป็นเจ้าของได้

create policy patient_conditions_select_own
on public.patient_conditions
for select
to authenticated
using (
  exists (
    select 1
    from public.patients
    where patients.id = patient_conditions.patient_id
      and patients.employer_id = (select auth.uid())
  )
);


-- Employer เพิ่มได้เฉพาะสภาวะที่เปิดใช้งาน
-- และต้องเป็นผู้ป่วยของตนเอง

create policy patient_conditions_insert_own
on public.patient_conditions
for insert
to authenticated
with check (
  exists (
    select 1
    from public.patients
    where patients.id = patient_conditions.patient_id
      and patients.employer_id = (select auth.uid())
      and patients.is_active = true
  )
  and exists (
    select 1
    from public.conditions
    where conditions.id = patient_conditions.condition_id
      and conditions.is_active = true
  )
);


-- Employer ลบความสัมพันธ์ได้เฉพาะผู้ป่วยของตนเอง

create policy patient_conditions_delete_own
on public.patient_conditions
for delete
to authenticated
using (
  exists (
    select 1
    from public.patients
    where patients.id = patient_conditions.patient_id
      and patients.employer_id = (select auth.uid())
  )
);

-- Employer อ่านทักษะที่ผู้ป่วยของตนเองต้องการได้

create policy patient_required_skills_select_own
on public.patient_required_skills
for select
to authenticated
using (
  exists (
    select 1
    from public.patients
    where patients.id = patient_required_skills.patient_id
      and patients.employer_id = (select auth.uid())
  )
);


-- Employer เพิ่มได้เฉพาะทักษะที่เปิดใช้งาน
-- และต้องเป็นผู้ป่วยของตนเอง

create policy patient_required_skills_insert_own
on public.patient_required_skills
for insert
to authenticated
with check (
  exists (
    select 1
    from public.patients
    where patients.id = patient_required_skills.patient_id
      and patients.employer_id = (select auth.uid())
      and patients.is_active = true
  )
  and exists (
    select 1
    from public.skills
    where skills.id = patient_required_skills.skill_id
      and skills.is_active = true
  )
);


-- Employer ลบความสัมพันธ์ได้เฉพาะผู้ป่วยของตนเอง

create policy patient_required_skills_delete_own
on public.patient_required_skills
for delete
to authenticated
using (
  exists (
    select 1
    from public.patients
    where patients.id = patient_required_skills.patient_id
      and patients.employer_id = (select auth.uid())
  )
);

-- Source: database/schema/06_patient_seed.sql
-- ข้อมูลตัวอย่างสำหรับใช้พัฒนาและทดสอบ MatchCare
-- ไม่ใช่มาตรฐานหรือคำวินิจฉัยทางการแพทย์

insert into public.conditions (
  name,
  description
)
values
  (
    'ต้องการความช่วยเหลือในกิจวัตรประจำวัน',
    'ต้องการผู้ช่วยในการทำกิจวัตรพื้นฐานประจำวัน'
  ),
  (
    'มีข้อจำกัดด้านการเคลื่อนไหว',
    'ต้องการความช่วยเหลือหรืออุปกรณ์ในการเคลื่อนไหว'
  ),
  (
    'ต้องเฝ้าระวังเป็นพิเศษ',
    'ต้องการผู้ดูแลคอยสังเกตอาการและความปลอดภัย'
  )
on conflict do nothing;

-- Source: database/schema/09_patient_atomic_save.sql
-- บันทึกข้อมูลผู้ป่วยและแท็กในคำสั่งเดียว เพื่อให้ล้มเหลว/สำเร็จพร้อมกัน
-- SECURITY INVOKER ใช้สิทธิ์และ RLS ของผู้เรียก ไม่ข้ามข้อจำกัดเจ้าของข้อมูล

create or replace function public.save_patient_with_tags(
  p_patient_id bigint,
  p_first_name text,
  p_last_name text,
  p_birth_date date,
  p_mobility_status text,
  p_care_notes text,
  p_province text,
  p_district text,
  p_subdistrict text,
  p_address_detail text,
  p_condition_ids bigint[],
  p_skill_ids bigint[]
)
returns public.patients
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
  v_patient public.patients;
begin
  if (select auth.uid()) is null then
    raise exception 'กรุณาเข้าสู่ระบบก่อนบันทึกข้อมูลผู้ป่วย';
  end if;

  if p_patient_id is null then
    insert into public.patients (
      employer_id, first_name, last_name, birth_date, mobility_status,
      care_notes, province, district, subdistrict, address_detail
    )
    values (
      (select auth.uid()), p_first_name, p_last_name, p_birth_date,
      p_mobility_status, p_care_notes, p_province, p_district,
      p_subdistrict, p_address_detail
    )
    returning * into v_patient;
  else
    update public.patients
    set first_name = p_first_name,
        last_name = p_last_name,
        birth_date = p_birth_date,
        mobility_status = p_mobility_status,
        care_notes = p_care_notes,
        province = p_province,
        district = p_district,
        subdistrict = p_subdistrict,
        address_detail = p_address_detail
    where id = p_patient_id
      and employer_id = (select auth.uid())
      and is_active = true
    returning * into v_patient;

    if not found then
      raise exception 'ไม่พบผู้ป่วยที่แก้ไขได้';
    end if;
  end if;

  delete from public.patient_conditions
  where patient_id = v_patient.id
    and not (condition_id = any(coalesce(p_condition_ids, '{}'::bigint[])));

  insert into public.patient_conditions (patient_id, condition_id)
  select v_patient.id, selected.condition_id
  from (
    select distinct unnest(coalesce(p_condition_ids, '{}'::bigint[])) as condition_id
  ) as selected
  on conflict do nothing;

  delete from public.patient_required_skills
  where patient_id = v_patient.id
    and not (skill_id = any(coalesce(p_skill_ids, '{}'::bigint[])));

  insert into public.patient_required_skills (patient_id, skill_id)
  select v_patient.id, selected.skill_id
  from (
    select distinct unnest(coalesce(p_skill_ids, '{}'::bigint[])) as skill_id
  ) as selected
  on conflict do nothing;

  return v_patient;
end;
$$;

revoke all on function public.save_patient_with_tags(
  bigint, text, text, date, text, text, text, text, text, text, bigint[], bigint[]
) from public, anon;

grant execute on function public.save_patient_with_tags(
  bigint, text, text, date, text, text, text, text, text, text, bigint[], bigint[]
) to authenticated;
