-- Source: database/schema/10_job_posts.sql
-- ID 4: ประกาศรับสมัครผู้ดูแลและทักษะที่ต้องการ
-- เก็บที่อยู่ในประกาศเป็น snapshot; ห้ามเปิดเผยตารางนี้ทั้งแถวแก่ผู้ใช้ทั่วไป

create table public.job_posts (
  id bigint generated by default as identity primary key,
  employer_id uuid not null references public.profiles(id) on delete restrict,
  patient_id bigint not null,
  title text not null,
  description text not null,
  care_summary text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  pay_amount numeric(10, 2) not null,
  pay_unit text not null,
  province text not null,
  district text not null,
  subdistrict text not null,
  address_detail text not null,
  status text not null default 'draft',
  published_at timestamptz,
  closed_at timestamptz,
  cancellation_reason text,
  cancelled_at timestamptz,
  cancelled_by uuid references public.profiles(id) on delete restrict,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint job_posts_patient_owner_fk
    foreign key (patient_id, employer_id)
    references public.patients(id, employer_id) on delete restrict,
  constraint job_posts_title_not_blank check (length(btrim(title)) > 0),
  constraint job_posts_description_not_blank check (length(btrim(description)) > 0),
  constraint job_posts_care_summary_not_blank check (length(btrim(care_summary)) > 0),
  constraint job_posts_dates_valid check (ends_at > starts_at),
  constraint job_posts_pay_positive check (pay_amount > 0),
  constraint job_posts_pay_unit_valid
    check (pay_unit in ('hour', 'day', 'month', 'total')),
  constraint job_posts_location_not_blank check (
    length(btrim(province)) > 0
    and length(btrim(district)) > 0
    and length(btrim(subdistrict)) > 0
    and length(btrim(address_detail)) > 0
  ),
  constraint job_posts_status_valid check (
    status in (
      'draft', 'open', 'closed', 'matched',
      'in_progress', 'completed', 'cancelled'
    )
  )
);

create index job_posts_employer_created_idx
on public.job_posts (employer_id, created_at desc);

create index job_posts_patient_active_idx
on public.job_posts (patient_id)
where status in ('open', 'matched', 'in_progress');

create index job_posts_open_location_idx
on public.job_posts (province, district, starts_at)
where status = 'open';

alter table public.job_posts enable row level security;

create trigger job_posts_set_updated_at
before update on public.job_posts
for each row execute function private.set_updated_at();

-- ป้องกันการเปิดประกาศของผู้ป่วยที่ปิดใช้งาน และกำหนดสถานะที่ ID 4 ใช้ได้
create or replace function private.validate_job_post()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
  v_check_patient boolean := true;
begin
  if tg_op = 'UPDATE' then
    v_check_patient := new.patient_id is distinct from old.patient_id
      or new.status is distinct from old.status;
  end if;

  if v_check_patient then
    if not exists (
      select 1 from public.patients
      where id = new.patient_id
        and employer_id = new.employer_id
        and is_active = true
    ) then
      raise exception using errcode = '23514',
        message = 'job_patient_must_be_active_and_owned';
    end if;
  end if;

  if tg_op = 'INSERT' then
    if new.status not in ('draft', 'open') then
      raise exception using errcode = '23514',
        message = 'job_initial_status_invalid';
    end if;
  elsif new.status is distinct from old.status then
    if not (
      (old.status = 'draft' and new.status in ('open', 'closed'))
      or (old.status = 'open' and new.status = 'closed')
    ) then
      raise exception using errcode = '23514',
        message = 'job_status_transition_invalid';
    end if;
  end if;

  if new.status = 'open' and new.published_at is null then
    new.published_at := now();
  end if;

  if new.status = 'closed' and new.closed_at is null then
    new.closed_at := now();
  end if;

  return new;
end;
$$;

create trigger job_posts_validate
before insert or update on public.job_posts
for each row execute function private.validate_job_post();

create table public.job_required_skills (
  job_post_id bigint not null references public.job_posts(id) on delete restrict,
  skill_id bigint not null references public.skills(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (job_post_id, skill_id)
);

create index job_required_skills_skill_id_idx
on public.job_required_skills (skill_id);

alter table public.job_required_skills enable row level security;

-- ตรวจตอนจบ transaction เพื่อให้เพิ่มประกาศและหลายทักษะพร้อมกันได้
create or replace function private.require_open_job_skill()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
  v_job_id bigint;
begin
  if tg_table_name = 'job_posts' then
    v_job_id := new.id;
  else
    v_job_id := old.job_post_id;
  end if;

  if exists (
    select 1 from public.job_posts
    where id = v_job_id and status = 'open'
  ) and not exists (
    select 1 from public.job_required_skills
    where job_post_id = v_job_id
  ) then
    raise exception using errcode = '23514',
      message = 'open_job_requires_skill';
  end if;

  return null;
end;
$$;

create constraint trigger job_posts_require_skill
after insert or update of status on public.job_posts
deferrable initially deferred
for each row execute function private.require_open_job_skill();

create constraint trigger job_required_skills_require_skill
after delete on public.job_required_skills
deferrable initially deferred
for each row execute function private.require_open_job_skill();

-- Source: database/schema/11_job_policies.sql
-- เจ้าของอ่านและจัดการประกาศของตน; ยังไม่เปิดตารางที่มีที่อยู่ละเอียดให้ผู้อื่นอ่าน

revoke all privileges on table public.job_posts from anon, authenticated;

grant select on table public.job_posts to authenticated;

grant insert (
  employer_id, patient_id, title, description, care_summary,
  starts_at, ends_at, pay_amount, pay_unit,
  province, district, subdistrict, address_detail, status
) on table public.job_posts to authenticated;

grant update (
  patient_id, title, description, care_summary,
  starts_at, ends_at, pay_amount, pay_unit,
  province, district, subdistrict, address_detail, status
) on table public.job_posts to authenticated;

grant usage, select on sequence public.job_posts_id_seq to authenticated;

create policy job_posts_select_own
on public.job_posts for select to authenticated
using ((select auth.uid()) = employer_id);

create policy job_posts_insert_own
on public.job_posts for insert to authenticated
with check (
  (select auth.uid()) = employer_id
  and exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'employer'
  )
);

create policy job_posts_update_own
on public.job_posts for update to authenticated
using (
  (select auth.uid()) = employer_id
  and status in ('draft', 'open')
)
with check (
  (select auth.uid()) = employer_id
  and exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'employer'
  )
);

-- ทักษะของประกาศอ่าน/เพิ่ม/ลบได้เฉพาะเจ้าของประกาศที่ยังแก้ไขได้
revoke all privileges on table public.job_required_skills from anon, authenticated;
grant select, insert, delete on table public.job_required_skills to authenticated;

create policy job_required_skills_select_own
on public.job_required_skills for select to authenticated
using (
  exists (
    select 1 from public.job_posts
    where id = job_required_skills.job_post_id
      and employer_id = (select auth.uid())
  )
);

create policy job_required_skills_insert_own
on public.job_required_skills for insert to authenticated
with check (
  exists (
    select 1 from public.job_posts
    where id = job_required_skills.job_post_id
      and employer_id = (select auth.uid())
      and status in ('draft', 'open')
  )
  and exists (
    select 1 from public.skills
    where id = job_required_skills.skill_id and is_active = true
  )
);

create policy job_required_skills_delete_own
on public.job_required_skills for delete to authenticated
using (
  exists (
    select 1 from public.job_posts
    where id = job_required_skills.job_post_id
      and employer_id = (select auth.uid())
      and status in ('draft', 'open')
  )
);

-- Source: database/schema/12_patient_open_job_guard.sql
-- ID 3 ข้อ 7: ผู้ป่วยที่ผูกกับประกาศ/งานที่ยังดำเนินอยู่ปิดใช้งานไม่ได้

create or replace function private.prevent_patient_deactivation_with_job()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if old.is_active = true and new.is_active = false and exists (
    select 1 from public.job_posts
    where patient_id = old.id
      and status in ('open', 'matched', 'in_progress')
  ) then
    raise exception using errcode = '23514',
      message = 'patient_has_active_job';
  end if;

  return new;
end;
$$;

create trigger patients_prevent_deactivation_with_job
before update of is_active on public.patients
for each row execute function private.prevent_patient_deactivation_with_job();

-- Source: database/schema/13_job_atomic_save.sql
-- สร้างประกาศกับทักษะใน transaction เดียว ภายใต้สิทธิ์/RLS ของผู้เรียก
create or replace function public.create_job_with_tags(
  p_patient_id bigint, p_title text, p_description text, p_care_summary text,
  p_starts_at timestamptz, p_ends_at timestamptz, p_pay_amount numeric,
  p_pay_unit text, p_skill_ids bigint[]
)
returns bigint language plpgsql security invoker set search_path = pg_catalog
as $$
declare
  v_job_id bigint;
  v_patient public.patients;
begin
  if auth.uid() is null then raise exception 'กรุณาเข้าสู่ระบบ'; end if;
  if not exists (select 1 from public.profiles where id = auth.uid() and role = 'employer') then
    raise exception 'เฉพาะผู้ว่าจ้างเท่านั้นที่สร้างประกาศได้';
  end if;

  -- ล็อกผู้ป่วยจนจบ transaction เพื่อไม่ให้ถูกปิดพร้อมกับเปิดประกาศ
  select * into v_patient from public.patients
  where id = p_patient_id and employer_id = auth.uid() and is_active for share;
  if not found then raise exception 'ไม่พบผู้ป่วยที่ใช้งานอยู่ในความดูแลของคุณ'; end if;
  if length(p_title) > 120 or nullif(btrim(p_title), '') is null
    or nullif(btrim(p_description), '') is null
    or nullif(btrim(p_care_summary), '') is null then
    raise exception 'กรุณากรอกข้อมูลประกาศให้ครบ และหัวข้อไม่เกิน 120 ตัวอักษร';
  end if;
  if coalesce(cardinality(p_skill_ids), 0) = 0 or exists (
    select 1 from unnest(p_skill_ids) requested(skill_id)
    left join public.skills skill on skill.id = requested.skill_id and skill.is_active
    where skill.id is null
  ) then raise exception 'กรุณาเลือกทักษะที่ใช้งานอยู่อย่างน้อย 1 รายการ'; end if;
  if p_starts_at is null or p_ends_at is null or not isfinite(p_starts_at)
    or not isfinite(p_ends_at) or p_ends_at <= p_starts_at then
    raise exception 'วันเวลาสิ้นสุดต้องอยู่หลังวันเวลาเริ่มงาน';
  end if;
  if p_pay_amount is null or p_pay_amount <= 0 or p_pay_amount > 99999999.99
    or p_pay_unit is null or p_pay_unit not in ('hour', 'day', 'month', 'total') then
    raise exception 'ค่าตอบแทนหรือหน่วยค่าตอบแทนไม่ถูกต้อง';
  end if;

  insert into public.job_posts (
    employer_id, patient_id, title, description, care_summary,
    starts_at, ends_at, pay_amount, pay_unit,
    province, district, subdistrict, address_detail, status
  ) values (
    auth.uid(), v_patient.id, btrim(p_title), btrim(p_description), btrim(p_care_summary),
    p_starts_at, p_ends_at, p_pay_amount, p_pay_unit,
    v_patient.province, v_patient.district, v_patient.subdistrict, v_patient.address_detail, 'draft'
  ) returning id into v_job_id;

  insert into public.job_required_skills(job_post_id, skill_id)
  select v_job_id, skill_id from (select distinct unnest(p_skill_ids) skill_id) requested;
  update public.job_posts set status = 'open' where id = v_job_id;
  return v_job_id;
end;
$$;
revoke all on function public.create_job_with_tags(bigint,text,text,text,timestamptz,timestamptz,numeric,text,bigint[]) from public, anon;
grant execute on function public.create_job_with_tags(bigint,text,text,text,timestamptz,timestamptz,numeric,text,bigint[]) to authenticated;

-- Source: database/schema/14_job_atomic_update.sql
create or replace function public.update_job_with_tags(
  p_job_id bigint,
  p_patient_id bigint,
  p_title text,
  p_description text,
  p_care_summary text,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_pay_amount numeric,
  p_pay_unit text,
  p_skill_ids bigint[]
)
returns bigint
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
  v_patient public.patients;
begin
  if auth.uid() is null then raise exception 'กรุณาเข้าสู่ระบบ'; end if;
  -- ล็อกประกาศเพื่อไม่ให้แก้ไขและปิดพร้อมกัน
  perform 1 from public.job_posts
  where id = p_job_id and employer_id = auth.uid() and status in ('draft', 'open')
  for update;
  if not found then raise exception 'ไม่พบประกาศที่แก้ไขได้ กรุณาโหลดรายการใหม่'; end if;
  select * into v_patient from public.patients
  where id = p_patient_id and employer_id = auth.uid() and is_active for share;
  if not found then raise exception 'กรุณาเลือกผู้ป่วยที่ใช้งานอยู่ของคุณ'; end if;
  if coalesce(length(btrim(p_title)), 0) = 0 or length(p_title) > 120
    or coalesce(length(btrim(p_description)), 0) = 0
    or coalesce(length(btrim(p_care_summary)), 0) = 0 then
    raise exception 'กรุณากรอกหัวข้อไม่เกิน 120 ตัวอักษร รายละเอียด และสรุปการดูแล';
  end if;
  if p_starts_at is null or p_ends_at is null or not isfinite(p_starts_at)
    or not isfinite(p_ends_at) or p_ends_at <= p_starts_at then
    raise exception 'วันเวลาสิ้นสุดต้องอยู่หลังวันเวลาเริ่มงาน';
  end if;
  if p_pay_amount is null or p_pay_amount <= 0 or p_pay_amount > 99999999.99
    or p_pay_unit is null or p_pay_unit not in ('hour','day','month','total') then
    raise exception 'ค่าตอบแทนหรือหน่วยค่าตอบแทนไม่ถูกต้อง';
  end if;
  if coalesce(cardinality(p_skill_ids), 0) = 0 or exists (
    select 1 from unnest(p_skill_ids) requested(id)
    left join public.skills s on s.id = requested.id and s.is_active
    where s.id is null
  ) then raise exception 'กรุณาเลือกทักษะที่ใช้งานอยู่อย่างน้อย 1 รายการ'; end if;
  update public.job_posts set patient_id = p_patient_id, title = btrim(p_title),
    description = btrim(p_description), care_summary = btrim(p_care_summary),
    starts_at = p_starts_at, ends_at = p_ends_at, pay_amount = p_pay_amount,
    pay_unit = p_pay_unit, province = v_patient.province, district = v_patient.district,
    subdistrict = v_patient.subdistrict, address_detail = v_patient.address_detail
  where id = p_job_id and employer_id = auth.uid();
  -- เพิ่มชุดใหม่ก่อนลบชุดเก่า; ถ้าล้มเหลว transaction จะย้อนกลับทั้งชุด
  insert into public.job_required_skills(job_post_id, skill_id)
  select p_job_id, id from (select distinct unnest(p_skill_ids) id) ids
  on conflict do nothing;
  delete from public.job_required_skills
  where job_post_id = p_job_id and not (skill_id = any(p_skill_ids));
  return p_job_id;
end;
$$;

revoke all on function public.update_job_with_tags(bigint,bigint,text,text,text,timestamptz,timestamptz,numeric,text,bigint[]) from public, anon;
grant execute on function public.update_job_with_tags(bigint,bigint,text,text,text,timestamptz,timestamptz,numeric,text,bigint[]) to authenticated;

create or replace function public.close_job(p_job_id bigint)
returns bigint language plpgsql security invoker set search_path = pg_catalog
as $$
declare v_id bigint;
begin
  update public.job_posts set status = 'closed'
  where id = p_job_id and employer_id = auth.uid() and status in ('draft', 'open')
  returning id into v_id;
  if v_id is null then raise exception 'ไม่พบประกาศที่ปิดได้ กรุณาโหลดรายการใหม่'; end if;
  return v_id;
end;
$$;
revoke all on function public.close_job(bigint) from public, anon;
grant execute on function public.close_job(bigint) to authenticated;
