-- รายการสภาวะและความต้องการดูแลสำหรับเลือกให้ผู้ป่วย
-- เป็นข้อมูลตัวอย่างสำหรับระบบ ไม่ใช่คำวินิจฉัยทางการแพทย์

create table public.conditions (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint conditions_name_not_blank
    check (length(btrim(name)) > 0),

  constraint conditions_description_not_blank
    check (
      description is null
      or length(btrim(description)) > 0
    )
);

create unique index conditions_name_unique
on public.conditions (lower(btrim(name)));

alter table public.conditions
enable row level security;

-- ข้อมูลผู้ป่วยที่อยู่ภายใต้การดูแลของ Employer

create table public.patients (
  id bigint generated by default as identity primary key,

  employer_id uuid not null
    references public.profiles(id) on delete restrict,

  first_name text not null,
  last_name text not null,
  birth_date date not null,
  mobility_status text not null,
  care_notes text,

  province text not null,
  district text not null,
  subdistrict text not null,
  address_detail text not null,

  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint patients_id_employer_unique
    unique (id, employer_id),

  constraint patients_first_name_not_blank
    check (length(btrim(first_name)) > 0),

  constraint patients_last_name_not_blank
    check (length(btrim(last_name)) > 0),

  constraint patients_mobility_status_valid
    check (
      mobility_status in (
        'bedridden',
        'wheelchair',
        'walker',
        'cane'
      )
    ),

  constraint patients_care_notes_not_blank
    check (
      care_notes is null
      or length(btrim(care_notes)) > 0
    ),

  constraint patients_address_not_blank
    check (
      length(btrim(province)) > 0
      and length(btrim(district)) > 0
      and length(btrim(subdistrict)) > 0
      and length(btrim(address_detail)) > 0
    )
);

create index patients_employer_id_idx
on public.patients (employer_id);

alter table public.patients
enable row level security;

-- ตรวจข้อมูลที่ Check Constraint แบบปกติครอบคลุมไม่ได้

create or replace function private.validate_patient()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if new.birth_date > current_date then
    raise exception using
      errcode = '23514',
      message = 'patient_birth_date_cannot_be_in_future';
  end if;

  if not exists (
    select 1
    from public.profiles
    where id = new.employer_id
      and role = 'employer'
  ) then
    raise exception using
      errcode = '23514',
      message = 'patient_owner_must_be_employer';
  end if;

  return new;
end;
$$;

create trigger patients_validate
before insert or update of birth_date, employer_id
on public.patients
for each row
execute function private.validate_patient();


-- ใช้ฟังก์ชัน updated_at ที่สร้างไว้ใน 03_updated_at_trigger.sql

create trigger conditions_set_updated_at
before update on public.conditions
for each row
execute function private.set_updated_at();

create trigger patients_set_updated_at
before update on public.patients
for each row
execute function private.set_updated_at();

-- เชื่อมผู้ป่วยกับสภาวะที่ต้องดูแล

create table public.patient_conditions (
  patient_id bigint not null
    references public.patients(id) on delete cascade,

  condition_id bigint not null
    references public.conditions(id) on delete restrict,

  created_at timestamptz not null default now(),

  primary key (patient_id, condition_id)
);

create index patient_conditions_condition_id_idx
on public.patient_conditions (condition_id);

alter table public.patient_conditions
enable row level security;


-- เชื่อมผู้ป่วยกับทักษะที่ต้องการจากผู้ดูแล

create table public.patient_required_skills (
  patient_id bigint not null
    references public.patients(id) on delete cascade,

  skill_id bigint not null
    references public.skills(id) on delete restrict,

  created_at timestamptz not null default now(),

  primary key (patient_id, skill_id)
);

create index patient_required_skills_skill_id_idx
on public.patient_required_skills (skill_id);

alter table public.patient_required_skills
enable row level security;