-- ID 4: ประกาศรับสมัครผู้ดูแลและทักษะที่ต้องการ
-- เก็บที่อยู่ในประกาศเป็น snapshot; ห้ามเปิดเผยตารางนี้ทั้งแถวแก่ผู้ใช้ทั่วไป

create table public.job_posts (
  id bigint generated by default as identity primary key,
  employer_id uuid not null references public.profiles(id) on delete restrict,
  patient_id bigint not null,
  title text not null,
  description text not null,
  care_summary text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  pay_amount numeric(10, 2) not null,
  pay_unit text not null,
  province text not null,
  district text not null,
  subdistrict text not null,
  address_detail text not null,
  status text not null default 'draft',
  published_at timestamptz,
  closed_at timestamptz,
  cancellation_reason text,
  cancelled_at timestamptz,
  cancelled_by uuid references public.profiles(id) on delete restrict,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint job_posts_patient_owner_fk
    foreign key (patient_id, employer_id)
    references public.patients(id, employer_id) on delete restrict,
  constraint job_posts_title_not_blank check (length(btrim(title)) > 0),
  constraint job_posts_description_not_blank check (length(btrim(description)) > 0),
  constraint job_posts_care_summary_not_blank check (length(btrim(care_summary)) > 0),
  constraint job_posts_dates_valid check (ends_at > starts_at),
  constraint job_posts_pay_positive check (pay_amount > 0),
  constraint job_posts_pay_unit_valid
    check (pay_unit in ('hour', 'day', 'month', 'total')),
  constraint job_posts_location_not_blank check (
    length(btrim(province)) > 0
    and length(btrim(district)) > 0
    and length(btrim(subdistrict)) > 0
    and length(btrim(address_detail)) > 0
  ),
  constraint job_posts_status_valid check (
    status in (
      'draft', 'open', 'closed', 'matched',
      'in_progress', 'completed', 'cancelled'
    )
  )
);

create index job_posts_employer_created_idx
on public.job_posts (employer_id, created_at desc);

create index job_posts_patient_active_idx
on public.job_posts (patient_id)
where status in ('open', 'matched', 'in_progress');

create index job_posts_open_location_idx
on public.job_posts (province, district, starts_at)
where status = 'open';

alter table public.job_posts enable row level security;

create trigger job_posts_set_updated_at
before update on public.job_posts
for each row execute function private.set_updated_at();

-- ป้องกันการเปิดประกาศของผู้ป่วยที่ปิดใช้งาน และกำหนดสถานะที่ ID 4 ใช้ได้
create or replace function private.validate_job_post()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
  v_check_patient boolean := true;
begin
  if tg_op = 'UPDATE' then
    v_check_patient := new.patient_id is distinct from old.patient_id
      or new.status is distinct from old.status;
  end if;

  if v_check_patient then
    if not exists (
      select 1 from public.patients
      where id = new.patient_id
        and employer_id = new.employer_id
        and is_active = true
    ) then
      raise exception using errcode = '23514',
        message = 'job_patient_must_be_active_and_owned';
    end if;
  end if;

  if tg_op = 'INSERT' then
    if new.status not in ('draft', 'open') then
      raise exception using errcode = '23514',
        message = 'job_initial_status_invalid';
    end if;
  elsif new.status is distinct from old.status then
    if not (
      (old.status = 'draft' and new.status in ('open', 'closed'))
      or (old.status = 'open' and new.status = 'closed')
    ) then
      raise exception using errcode = '23514',
        message = 'job_status_transition_invalid';
    end if;
  end if;

  if new.status = 'open' and new.published_at is null then
    new.published_at := now();
  end if;

  if new.status = 'closed' and new.closed_at is null then
    new.closed_at := now();
  end if;

  return new;
end;
$$;

create trigger job_posts_validate
before insert or update on public.job_posts
for each row execute function private.validate_job_post();

create table public.job_required_skills (
  job_post_id bigint not null references public.job_posts(id) on delete restrict,
  skill_id bigint not null references public.skills(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (job_post_id, skill_id)
);

create index job_required_skills_skill_id_idx
on public.job_required_skills (skill_id);

alter table public.job_required_skills enable row level security;

-- ตรวจตอนจบ transaction เพื่อให้เพิ่มประกาศและหลายทักษะพร้อมกันได้
create or replace function private.require_open_job_skill()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
  v_job_id bigint;
begin
  if tg_table_name = 'job_posts' then
    v_job_id := new.id;
  else
    v_job_id := old.job_post_id;
  end if;

  if exists (
    select 1 from public.job_posts
    where id = v_job_id and status = 'open'
  ) and not exists (
    select 1 from public.job_required_skills
    where job_post_id = v_job_id
  ) then
    raise exception using errcode = '23514',
      message = 'open_job_requires_skill';
  end if;

  return null;
end;
$$;

create constraint trigger job_posts_require_skill
after insert or update of status on public.job_posts
deferrable initially deferred
for each row execute function private.require_open_job_skill();

create constraint trigger job_required_skills_require_skill
after delete on public.job_required_skills
deferrable initially deferred
for each row execute function private.require_open_job_skill();
